//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranHoangDinh_2120110042.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public int CateId { get; set; }
        public string CateName { get; set; }
    }
}
